### ISSUE TITLE
HDMI audio not working

### ISSUE THREAD

**Issue by tmthang86** [hackintosh-efi/intel-nuc10#1]
The HDMI video was ok, but HDMI audio wasn't.

**Comment by mrasong** [comment]
not fixed yet, you can use a TypeC to HDMI Hub as an alternative.

**Comment by basett1** [comment]
I don't really like this solution but use VoodooHDA, it works. i'm working on this NUC, soon i create repo.

**Comment by mrasong** [comment]
> I don't really like this solution but use VoodooHDA, it works. i'm working on this NUC, soon i create repo.

VoodooHDA works, but not works so good, so I didn't release that version

**Comment by basett1** [comment]
> > I don't really like this solution but use VoodooHDA, it works. i'm working on this NUC, soon i create repo.
> 
> VoodooHDA works, but not works so good, so I didn't release that version

Yes, It's Just a temporary workaround, with our team we are working on this issue. If we have news i tell you.

**Comment by mrasong** [comment]
> The HDMI video was ok, but HDMI audio wasn't.

https://github.com/hackintosh-efi/intel-nuc10/releases/tag/v0.6.5.0119

new efi with VoodooHDA.kexts fixed this.

**Comment by tmthang86** [comment]
> > The HDMI video was ok, but HDMI audio wasn't.
> 
> https://github.com/hackintosh-efi/intel-nuc10/releases/tag/v0.6.5.0119
> 
> new efi with VoodooHDA.kexts fixed this.

Wow, thanks mrasong, its a good new
