### ISSUE TITLE
CFG Unlock

### ISSUE THREAD

**Issue by devgiangtm** [hackintosh-efi/intel-nuc10#10]
I just format USB to fast32 and copy EFI to USB but when i press F10 and boot to USB. only show window 10 option. I cant see CFG unlock or VerifyMsrE2. Can you help me ?

**Comment by mrasong** [comment]
make sure your USB drive was formated as fat32 and the EFI dir must be /EFI.

**Comment by devgiangtm** [comment]
what else if skip this step ? My USB drive was formated as fat32 and only has EFI folder inside :(

**Comment by mrasong** [comment]
so did you enable boot from usb drive?

**Comment by devgiangtm** [comment]
I have successfully installed. However, every time I shutdown the computer it automatically turns on again. Have you got this error?

**Comment by mrasong** [comment]
try to disable wake on lan  and some power options in BIOS

**Comment by devgiangtm** [comment]
thank you so much <3
