### ISSUE TITLE
Automatic restart after shutdown

### ISSUE THREAD

**Issue by gfab-io** [hackintosh-efi/intel-nuc10#11]
Hi, I'm on NUC10i7FNH, CFG Unlock and installed Big Sur without any problems.
I'm experiencing always the automatic restart just after shutdown (but if I shutdown from the login screen, it power off regularly). 
I've disabled Wake from network in system preferences, but that didn't fix it. 
I read in another post to change some bios settings in the Power section, but which one specifically?  Has anyone had the same problem and fixed it some way?

**Comment by gfab-io** [comment]
I forgot to mention that I'm on the latest bios 0047

**Comment by mrasong** [comment]
Duplicate of #10

**Comment by mrasong** [comment]
try to disable 
 - wake from thunderbolt device
 - wake on lan
 - wake on lan from s4/s5

**Comment by gfab-io** [comment]
Thanks, that worked!
