### ISSUE TITLE
BigSur Beta 11.3 Not HDMI Sound

### ISSUE THREAD

**Issue by hkodroidc2** [hackintosh-efi/intel-nuc10#12]
I got an update today. 11.3 
I updated and then HDMI does not sound

**Comment by mrasong** [comment]
enable VoodooHDA.kext
disable AppleALC.kext

**Comment by enderaltin** [comment]
exactly, but not coming out with the beta 11.3 update

**Comment by enderaltin** [comment]
enable VoodooHDA.kext
disable AppleALC.kext
my settings are as above

HDMI Audio does not work. With the beta 11.3 update

**Comment by mrasong** [comment]
It may also be a problem with the beta system

**Comment by enderaltin** [comment]
how can i go back

**Comment by mrasong** [comment]
> how can i go back

back to 11.2.1?

**Comment by enderaltin** [comment]
> > how can i go back
> 
> back to 11.2.1?

yes

**Comment by enderaltin** [comment]
?

**Comment by mrasong** [comment]
Did you backup your data with timemachine?
TM may be the best way to back to 11.2.1 with full of your datas.

**Comment by hotsticker** [comment]
@enderaltin, did HDMI work again with 11.3.1?  I'm thinking of upgrading to that, but want to keep HDMI audio.  Thanks for sharing your experience with us
