### ISSUE TITLE
no turnoff

### ISSUE THREAD

**Issue by snami100** [hackintosh-efi/intel-nuc10#13]
Hello, 
at first thanks for your work.
When im turning off my nuc it doesnt turn off it just reboots. (in macOS)

Best regards

**Comment by mrasong** [comment]
BIOS 

Power -> Secondary Power Settings
Deep S4/S5 -> ON
Wake on Lan from S4/S5 -> Stay Off
Wake System from S5 -> Off

**Comment by mrasong** [comment]
#11
