### ISSUE TITLE
SD card is not working

### ISSUE THREAD

**Issue by coopsrc** [hackintosh-efi/intel-nuc10#14]
Version: v0.6.6.0202
Device: NUC10i7FNH/FNK
OS Version: macOS Big Sur 11.2.2

**Comment by mrasong** [comment]
There is no SD card driver yet.

**Comment by mbarbierato** [comment]
Try to add this configuration in config.plist
![Schermata 2021-04-09 alle 08 31 49](https://user-images.githubusercontent.com/5329826/114138520-09ec3900-990e-11eb-8f56-38588867ab2d.png)

**Comment by mrasong** [comment]
> Try to add this configuration in config.plist
> ![Schermata 2021-04-09 alle 08 31 49](https://user-images.githubusercontent.com/5329826/114138520-09ec3900-990e-11eb-8f56-38588867ab2d.png)

Did the SD card work after you add this config ?
This may only displays the SD card info , but not works.

**Comment by mbarbierato** [comment]
> > Try to add this configuration in config.plist
> > ![Schermata 2021-04-09 alle 08 31 49](https://user-images.githubusercontent.com/5329826/114138520-09ec3900-990e-11eb-8f56-38588867ab2d.png)
> 
> Did the SD card work after you add this config ?
> This may only displays the SD card info , but not works.

In nuc10i5fnh work i',ve fixed on my friend , this is your repo https://github.com/pierpaolodimarzo/Intel-NUC10i5FNH
