### ISSUE TITLE
0.6.7 and 0.6.6 will not boot

### ISSUE THREAD

**Issue by delija999** [hackintosh-efi/intel-nuc10#15]
hi,
i can not boot with 067 and 066. it will not start opencore.
065 works fine.

nuc10i7, big sur 11.2.1

**Comment by mrasong** [comment]
make sure there is an `EFI` folder in the root of EFI patition. If you did so, which step you got an error? nothing displays or just the apple logo？can you give a screenshot?

**Comment by delija999** [comment]
i got it. OC was on EFI/OC/Bootstrap/Bootstrap.efi. i change it on EFI/OC/OpenCore.efi and it works.
thx

**Comment by enderaltin** [comment]
I updated it with the EFI here, but the OpenCore version appears to be 0.6.6. Why is that ?

**Comment by mrasong** [comment]
> I updated it with the EFI here, but the OpenCore version appears to be 0.6.6. Why is that ?

Where did you see the version? In hackintool ?
Some one already updated to 0.6.7 but still show 0.6.5.
You can find the latest version build info(2021-03-01) at the OC booting srceen.
Maybe you can reset NVRAM ?

**Comment by delija999** [comment]
reset NVRAM. 
attention: after reset there is no more OC in boot. 

on OC boot screen you can see what version you have.

**Comment by mrasong** [comment]
if you have both windows and macOS on one disk, the OC boot will be covered by the Windows MBR after reset NVRAM.
You need add it back in windows systems.

may be the version shown in hackintool is a bug. 
[Hackintool doesn't detect OpenCore 0.6.7 #128](https://github.com/headkaze/Hackintool/issues/128)
