### ISSUE TITLE
wol(wake on lan) doesn't work in mac os

### ISSUE THREAD

**Issue by chunfengyao** [hackintosh-efi/intel-nuc10#16]
wol(wake on lan) works fine in windows 10, but not mac os.
The intel lan interface was powered off when mac os shutdown.

**Comment by chunfengyao** [comment]
wol(wake on lan) works fine in windows 10, but not mac os.
The intel lan interface was powered off when mac os shutdown.

**Comment by mrasong** [comment]
may be you should turn on the  `Deep S4/S5` in bios ?

**Comment by mrasong** [comment]
You can keep NUC on all the time, if you have the remote needs to use it.
I never turn it off, unless it is on a business trip or out for many days.

After all, this is a hackintosh.  :)

**Comment by chunfengyao** [comment]
@mrasong all right, thanks.
