### ISSUE TITLE
Dualscreen not working at startup!

### ISSUE THREAD

**Issue by AngealGeek** [hackintosh-efi/intel-nuc10#17]
Hello! thanks for your EFi!

I just saw than my hackintosh can't boot with dual screen plugged (HDMI+usb c) ==+> crash on Apple Logo

But if i plugged the second cable only after the loading screen everything works well.

i have an nuc10i3fnk2 but i tried another EFI on internet for the Nuc 08 just in case, and its seems to works (but of course i have a lot of others problem with this one.

Here is the NUC 10 with your Vanilla EFI, i plugged my converter when already running and everything smooth well
https://drive.google.com/file/d/1c4tNbHxihjTKgNLVBgdZuEPeEFtDV89Y/view?usp=sharing

Boot with everything plugged:
https://drive.google.com/file/d/1c21KlpEDaA9aYIWpJ7ke-usw1Vc5nE6T/view?usp=sharing

thanks for your time!

**Comment by mrasong** [comment]
It‘s really a like what you said.
Two ways to solve this problem：
1. Set your primary monitor to Thunderbolt device in BIOS.
2. Unplug the Type-C cable at startup, and plug it again while you already logged in.

**Comment by AngealGeek** [comment]
Thans for your quick answer.

I tried to set the primary monitor to thunderbolt but unfortunaly it didnt work for me.

Is there a way to totaly disable dual screen in the EFI?

I dont really want to use two screen on the nucintosh, but i have a dualboot with windows and its a bit annoying to unplugged the thunderbolt cable every time i want to use big sur.

**Comment by mrasong** [comment]
you need use dualscreen in windows but one in Big Sur?
Or just one disk with both macOS and Windows?
My way is keeping the nuc on all the time ;)

**Comment by AngealGeek** [comment]
"you need use dualscreen in windows but one in Big Sur?" ==> exatly!

So even if i keep the nuc on, i still have to reboot to switch between Mac and Windows

I will unplugged the cable THUNDERBOLT until another solution is found, thank you and i keep you informed!

**Comment by mrasong** [comment]
It seems no good ways to fix this problem.

**Comment by fschaal** [comment]
@AngealGeek, a workaround that I found was to turn off the thunderbolt display at boot. And turn it back on at login. That way you do not have to keep plugging in/out cabels.
