### ISSUE TITLE
"Internet connection required"

### ISSUE THREAD

**Issue by kimjongyoung** [hackintosh-efi/intel-nuc10#18]
Hi there,

I followed instructions from https://www.tonymacx86.com/threads/guide-booting-the-usb-installer-using-opencore.296375/ and copied EFI folder at top directory.

When I boot from the disk I made, I was prompted with the message "Internet connection required"

What should I do at this point?

**Comment by mrasong** [comment]
Seems your USB drive was not correct bootable？
EFI folder should put into the ROOT of the EFI patation  with name the EFI.

**Comment by kimjongyoung** [comment]
Thank you for advice.
The internet connection issue disappears simply by changing the volume name into "EFI".
But now I face new one, when the installer asked me to choose installation disk, it says "it is not designed as guid"
I looked at the HFS+ partition using paragon, its type is MBR.

**Comment by mrasong** [comment]
when you in the install step , first open disk util and format your DISK to APFS with GUID patation map. 
And then begain to install macOS.
