### ISSUE TITLE
press power button take no action.

### ISSUE THREAD

**Issue by chenyg0911** [hackintosh-efi/intel-nuc10#20]
Latest EFI(oc 0.6.8), NUC10i5FNH

Hope it sleep/hibernate/lock screen, but it no any action.

Command-Option-PowerButton worked Or through System menu.

have set bios as suggestion:
Secondary Power Settings
Deep S4/S5 -> On
Wake on Lan from S4/S5 -> Stay Off
Wake System from S5 -> Off
Wake From Thunderbolt Device -> Off

What's the problem?

**Comment by mrasong** [comment]
We are hackintosh ;)  Don not care about these details. 
BTW, I think it's more convenient by click ths sleep menu.

**Comment by chenyg0911** [comment]
ennn...., Just some inconenience. Thank you supply the EFI.
