### ISSUE TITLE
bluetooth keyboard & mouse not working

### ISSUE THREAD

**Issue by dogfriend79** [hackintosh-efi/intel-nuc10#22]
Hello

I'm using it very well, thank you very much.

There's one problem.

The Bluetooth keyboard mouse doesn't recognize it.

However, Apple's official keyboard and mouse are well recognized.

What could be the problem?

Razer keyboard mouse and Microsoft designer mouse and keyboard

Both are not working.

Please help me.

Thank you always.

**Comment by mrasong** [comment]
The bluetooth driver does not support BT4.0 or 5.0 devices yet.
