### ISSUE TITLE
SATA drive not writeable, intermittent booting freezes

### ISSUE THREAD

**Issue by elabjer** [hackintosh-efi/intel-nuc10#23]
Hi.

I couldn't get Big Sur to install on my nuc10i5fnh, but Catalina did, though it has some issues.. 

#1: I've installed it to NVME and wanted to use the second SATA drive for TM backups, but I can't write to, nor format, this drive.. I've read around about issues with generic sata in appleahci, but the proposed patching seems beyond my current ability.
Is someone able to provide this patched kext?

#2: booting has glitches. it seems to work 3/5 times w/o an issue, but when it doesn't it either freezes at apple logo, or displays the prohibited sign. a reboot typically solves it, though sometimes I need to do a few in a row. is there an obvious fix for this?

**Comment by HawkysCC** [comment]
Can computer read the SATA hard drive?If it can,obviously it's not kext problem.

**Comment by elabjer** [comment]
it shows up in OSX, files are listed, but any actual read produces an error. attempt to. format it also produces an error. the drive is fine tho.
