### ISSUE TITLE
about serial number

### ISSUE THREAD

**Issue by WorkerYifei** [hackintosh-efi/intel-nuc10#24]
Should I generate a new SN and modify the config.plist file?   If needed, when should I do that? before install or after install?

**Comment by chenyg0911** [comment]
You can copy the SN from you old config.plist, replace the lines in new config.plist.

**Comment by WorkerYifei** [comment]
> You can copy the SN from you old config.plist, replace the lines in new config.plist.

I have installed big sur on my Nuc10 successfully, thanks~
