### ISSUE TITLE
latest bios works?

### ISSUE THREAD

**Issue by alexookah** [hackintosh-efi/intel-nuc10#29]
I checked that the latest bios is:
[0053](https://www.intel.com/content/www/us/en/download/19485/bios-update-fncml357.html )

Does everything work as expected?

**Comment by mrasong** [comment]
> I checked that the latest bios is:
> [0053](https://www.intel.com/content/www/us/en/download/19485/bios-update-fncml357.html)
> 
> Does everything work as expected?

works well.

**Comment by alexookah** [comment]
Ok maybe update readme bios version?

**Comment by mrasong** [comment]
updated
