### ISSUE TITLE
VoodooHda and AppleALC

### ISSUE THREAD

**Issue by alexookah** [hackintosh-efi/intel-nuc10#3]
Checked in this site: https://opencore.slowgeek.com/
using the config.plist (which should contain only AppleALC.kext)

there is this warning: `AppleALC.kext don't use both VoodooHDA.kext and AppleALC.kext`
why does config.plist use both audio drivers?

**Comment by mrasong** [comment]
config.plist add both `AppleALC.kext ` and `VoodooHDA.kext `, but only enabled one of them.

**Comment by alexookah** [comment]
which one gets enabled?
can i remove the VoodooHDA and use only AppleALC ?

**Comment by mrasong** [comment]
### config.plist

- `/EFI/OC/config.plist` Default boot with `AppleALC.kext`.
- `/EFI/OC/config.VoodooHDA.plist` Default boot with `VoodooHDA.kext`(HDMI Audio works).
- `/EFI/OC/config.UI.plist` GUI boot with `AppleALC.kext`.
- `/EFI/OC/config.UI.VoodooHDA.plist` GUI boot with `VoodooHDA.kext`(HDMI Audio works).

choose one that you prefer to.

**Comment by alexookah** [comment]
OK.
Now i did a a check in config.plist and found that VoodooHDA is added but disabled.
<key>Enabled</key>
<false/>

Ok closing this issue
Thank you
