### ISSUE TITLE
readme confusion

### ISSUE THREAD

**Issue by alexookah** [hackintosh-efi/intel-nuc10#30]
It makes sense to have a description on how to use this repo. I am not 100% sure if I used the repo correctly.

1. Download repo.
2. Use one of these configs and rename to `config.plist`.
```
/EFI/OC/config.plist Default boot with AppleALC.kext.
/EFI/OC/config.VoodooHDA.plist Default boot with VoodooHDA.kext(HDMI Audio works).
/EFI/OC/config.UI.plist GUI boot with AppleALC.kext.
/EFI/OC/config.UI.VoodooHDA.plist GUI boot with VoodooHDA.kext(HDMI Audio works).
```

3. change the PlatformInfo-> MLB, SystemSerialNumber, SystemUUID & ROM.
4. Copy EFI files to the root of your USB drive, path will be /EFI.
5. Reboot your nuc10, press F10, boot with the drive above and see if everything works.

is this corect?

**Comment by alexookah** [comment]
What is the difference `config.plist` with `config.AppleALC.plist`?

**Comment by mrasong** [comment]
> C

`config.plist` just a copy of `config.AppleALC.plist`

**Comment by alexookah** [comment]
ok thanks
