### ISSUE TITLE
no sound

### ISSUE THREAD

**Issue by dogfriend79** [hackintosh-efi/intel-nuc10#34]
Hello
Thank you so much for this update.
But there's a problem.
No sound output device was found.
The sound is not coming out.
Please help me.

**Comment by freeants** [comment]
Same here. OC74

**Comment by dogfriend79** [comment]
Headphone output

**Comment by dogfriend79** [comment]
> Same here. OC74

Whats ploblem?

**Comment by mrasong** [comment]
fixed

**Comment by dogfriend79** [comment]
Thank you so much 😃
