### ISSUE TITLE
Cannot install Monterey

### ISSUE THREAD

**Issue by chengrutw** [hackintosh-efi/intel-nuc10#38]
I'm able to successfully download Monterey installer via OTA but can't initiate the installation process

**Comment by dogfriend79** [comment]
im monterey using 

no ploblem

**Comment by a00110110011** [comment]
Huge problems.... screen freezes after 2 minutes
keeping this link alive for more help..

**Comment by mrasong** [comment]
> Huge problems.... screen freezes after 2 minutes keeping this link alive for more help..

If you enable FakePCIID and FakePCIID_Intel_HDMI_Audio, this will happen.

use the config.monterey.plist.

**Comment by dogfriend79** [comment]
monterey When will the sound come out?

**Comment by mrasong** [comment]
OK now
