### ISSUE TITLE
Bios config

### ISSUE THREAD

**Issue by alexookah** [hackintosh-efi/intel-nuc10#4]
It would be great if there was some small info about the bios configuration in order to successfully boot.

**Comment by mrasong** [comment]
I'll give a BIOS config later.

**Comment by mrasong** [comment]
### BIOS config

- Advanced -> Storage -> SATA Mode Selection -> AHCI
- Boot -> Secure Boot -> Secure Boot -> Disabled
- Boot -> UEFI Boot -> Checked
- Boot -> Legacy Boot -> Unchecked
- Boot -> Fast Boot -> Unchecked

keep other settings default.

also updated README.

**Comment by alexookah** [comment]
nice @mrasong 
thanks
