### ISSUE TITLE
Question re: 0.7.5 version here

### ISSUE THREAD

**Issue by DWomack** [hackintosh-efi/intel-nuc10#40]
In config.plist under Platforminfo>Generic I see MLB, SystemSerialNumber, and SystemUUID all blank.
ROM has a place holder.
Does this version now auto populate these fields, or do I need to run GenSMBIOS and populate the fields?
Or can I just use the ones in the current 18 month old config.plist?

Thanks for your help and letting us follow along with your work.

Dennis

**Comment by dogfriend79** [comment]
GenSMBIOS run !!
