### ISSUE TITLE
Can't I  direct upgrade from Bigsur to Monterey.

### ISSUE THREAD

**Issue by chenyg0911** [hackintosh-efi/intel-nuc10#41]
Or I have reinstall to upgrade Monterey?

**Comment by mrasong** [comment]
> Or I have reinstall to upgrade Monterey?

upgrade OC to 0.7.5 and then direct upgrade.


WARNING!!!

when you upgrade to Monterey, you may not use onboard audio. You can use a typec or bluetooth device instead.

**Comment by chenyg0911** [comment]
Great! Will try it soon. Thanks!
