### ISSUE TITLE
monterey hdmi audio not working

### ISSUE THREAD

**Issue by daiyifei** [hackintosh-efi/intel-nuc10#43]
no sound without Fakexxx，but freezing screen when enable them

**Comment by dogfriend79** [comment]
Same here but i using BT earphone

**Comment by daiyifei** [comment]
> Same here but i using BT earphone
Maybe BT is only way,Both onboard audio and hdmi audio don't work without fakepciid.kext.Don't know what to do.

**Comment by mrasong** [comment]
now fixed.

**Comment by dogfriend79** [comment]
thx
