### ISSUE TITLE
volume hash mismatch

### ISSUE THREAD

**Issue by shrisha108** [hackintosh-efi/intel-nuc10#45]
Yesterday I installed Monterey on NUC 10th gen i5 with your EFI and everything is working and super smooth.
Thank you very much.
Only the issue I got this morning is this notification: volume hash mismatch macos should be reinstalled on this volume. What could be a cause of this? 
Thank you.

**Comment by mrasong** [comment]
Audio issue fixed in the latest EFI, you may try to update it.
