### ISSUE TITLE
New install, Apple logo followed by crash and reboot

### ISSUE THREAD

**Issue by Bramzor** [hackintosh-efi/intel-nuc10#48]
I've installed macOS_11.6.1-20G224 on a new NUC10i3FNKH2 with a Samsung 980 M.2 drive.
Installation was running fine (so I assume everything was compatible) but after an automated reboot of the installer, it got stuck in a reboot loop.
When booting from USB using F10 it shows the Apple logo followed by trying to access the NVME drive (HD LED lights up for a second) and it crashes and reboots again.

I thought the installer screwed up the USB drive EFI so I recreated the drive but still same result. So it's not a problem with the EFI on the USB drive or the installation files.
The USB drive worked before and during the MacOS installation but started failing after the installation. It just crashes after showing the logo and is stuck in this loop.

Is it possible to create a new branch EFI version with all logging enabled to troubleshoot this issue? Checked the EFI drive but could only find some screenshots that only show the apple logo.

**Comment by Bramzor** [comment]
Is it possible that the NVME fix is required before installation?

**Comment by kababoom** [comment]
Got a NUC10i3FNK2 also with Samsung SSD and is working fine.

Did you do all bios settings? also make sure that for Monterey you use the Monterey config.

**Comment by Bramzor** [comment]
> Did you do all bios settings? also make sure that for Monterey you use the Monterey config.

Yes, did set all the bios settings that are mentioned. Also did the CFG unlock but my Nuc returns 2 CFG values. Tried to set both of them but seems to only work for the CPU though.
Tried to install both Catalina and Big Sur, same issues. Really looks drive related but odd that it fails on both of them.
One of the last message in the installation log before the crash (tried to film it using slow motion) for Catalina:
`disk2s1 is not convertible to APFS...`
Which is odd because the disk was formatted in APFS with GUID.
After that line or maybe 1-2 other lines the system crashes.

Even tried another strategy where I cloned the disk of an existing Mac mini system in order to test it on the NUC but apparently none of the tools (CCC or SuperDuper) creates a copy of the boot itself? In the boot options I see the specific tools like CFGFix etc which are on the EFI (and therefore not overwritten), but no option to boot from that cloned drive.

**Comment by kababoom** [comment]
CFGFix did not work for me, also the new ControlMsrE2 did not but still working fine without it.

Just checked the disk and partitioning in this particular box for you (Samsung 970 EVO Plus)
<img width="684" alt="image" src="https://user-images.githubusercontent.com/16404944/144455659-f5bba610-2dd1-4100-9ebc-b794258ea451.png">

The CCC disk will boot if you create a EFI partition on it and add the EFI from this repo.. Other option perhaps is to use CloneZilla to fully image the disk from your other mini, restore it to your NUC but make sure to have the EFI partition with all from this repo.

**Comment by Bramzor** [comment]
> The CCC disk will boot if you create a EFI partition on it and add the EFI from this repo.. Other option perhaps is to use CloneZilla to fully image the disk from your other mini, restore it to your NUC but make sure to have the EFI partition with all from this repo.

I did use CCC and SuperDuper and bot times the same result. If I try to boot from that M.2 it will still have the old EFI on it which is the EFI from this git. And with that EFI it does not show the option to boot from that cloned OS for some reason. So either it did not clone the boot parts or something like that.

Also installing from scratch seems not a valid option for an unknown reason with either the 2 NVME drives or partitioning. (Tried both Big Sur which uses HFS and Catalina which uses APFS, both failing).

So either it does not work with this specific NUC or I'm missing something.

**Comment by kababoom** [comment]
Do you press space if there's one boot option?

CCC and SuperDuper create copies of the disk files, CloneZilla creates an image like remember Norton Ghost...

**Comment by Bramzor** [comment]
> Do you press space if there's one boot option?
> 
> CCC and SuperDuper create copies of the disk files, CloneZilla creates an image like remember Norton Ghost...

0 boot options.

Did some more tests.
What I did is a fresh Mac OS installation using a Macbook Pro on the specific drive. Macbook Pro could just boot from that new installation. Connected the drive to the NUC and it was not able to find any bootable drives (because EFI was still missing which is expected right?). So I mounted the drive, placed the EFI from this git on it and booted from the drive. Result: no bootable drive options. Only see UEFI Shell, CFGLock Shell and Reset NVRAM.
My guess is that it just does not work on this NUC10i3FNKH2 NUC.
What is the difference between and NUC10i3FNKH2 and NUC10i3FNH/FNK that could cause this issue?

**Comment by kababoom** [comment]
Hmm that's strange... don't think it's this EFI that's the issue..

In EFI Shell, can you goto the disk and ls things? just type something like fs0 (or fs1 or usb) then ls.. or view the mapping table? What Bios version are you on? wonder if there's a new setting preventing booting. 
Did you look at other sources like TonyMacX86? use some filtering glasses there though...

Will see if I can create a simple EFI usb from which I can boot from but that will not be this weekend.. As a final test I could create a disk image of a complete working drive.

**Comment by HawkysCC** [comment]
Hard drive problem,not EFI.

**Comment by fre4ki** [comment]
I had the same problem with installing macOS Ventura on NUC10i7 with Samsung 980 Pro (2TB). I'm was using the disk utility and installed it with MacOS Extended (Journaled).

After i format the disk with **APFS** the installation running through and everything is working.
