### ISSUE TITLE
No Audio device found while using v0.7.8.0207 OpenCore 0.7.8

### ISSUE THREAD

**Issue by essereio** [hackintosh-efi/intel-nuc10#51]
![Screen Shot 2022-02-11 at 8 39 21 AM](https://user-images.githubusercontent.com/96088484/153601756-bab5372a-5ff1-4396-a4eb-822c11179b34.png)

Intel NUC10i3FNH - Monterey

BIOS is updated to latest version. FNCML357.0055

**Comment by mrasong** [comment]
rollback now, please use the lastest version updated just now.

**Comment by essereio** [comment]
I ended up copying&replacing Lilu.kext 1.6.0, WhateverGreen.kext 1.5.7 and AppleALC.kext 1.6.9 into previous version 0.7.7 and it works fine. I will try the updated 0.7.8 later.

alcid needs to be changed to 24 to display the “Audio line-in port” in Sound settings however the 3.5mm front line in port still does not work with the microphone on headphones. Audio output on headphones does work though. Do you have a solution for making the microphone work on 4 pole headphones?

AppleALC
v1.6.6
Added ALC256 layout-id 24 for Intel NUC NUC10i5FNH by Andres ZeroCross
https://github.com/andreszerocross/AppleALC

**Comment by mrasong** [comment]
> 

Just display "Audio line-in port", but not works?

**Comment by essereio** [comment]
Yes. Not work. Does "Audio line-in port" work for you with headphones+mic?

**Comment by migrsoft** [comment]
v0.7.5.1123 is work well on my nuc10i7 with Monterey.

**Comment by essereio** [comment]
> v0.7.5.1123 is work well on my nuc10i7 with Monterey.

I just tried "[v0.7.5.1102 OpenCore 0.7.5 Monterey Audio Fixed](https://github.com/hackintosh-efi/intel-nuc10/releases/tag/v0.7.5.1123)" and I still don't see the Headphones port microphone
![Screen Shot 2022-02-17 at 3 02 12 AM](https://user-images.githubusercontent.com/96088484/154431821-ed326ed6-9f82-478e-b81c-89438fcb7372.png)

Can I see a picture of your settings?

**Comment by mrasong** [comment]
Same to you.
I use a USB-C headphone with microphone instead.

**Comment by migrsoft** [comment]
> > v0.7.5.1123 is work well on my nuc10i7 with Monterey.
> 
> I just tried "[v0.7.5.1102 OpenCore 0.7.5 Monterey Audio Fixed](https://github.com/hackintosh-efi/intel-nuc10/releases/tag/v0.7.5.1123)" and I still don't see the Headphones port microphone... ![Screen Shot 2022-02-17 at 3 02 12 AM](https://user-images.githubusercontent.com/96088484/154431821-ed326ed6-9f82-478e-b81c-89438fcb7372.png) Can I see a picture of your settings?

Yes, headphone input is missing, only internal microphone exists.
