### ISSUE TITLE
Can't connect to personal hotspot.

### ISSUE THREAD

**Issue by tmgiang95** [hackintosh-efi/intel-nuc10#53]
I'm using Nuc10i5fnh running on version 12.3 Monterey. I can connect to 2.4Ghz wifi but can't connect to mobile personal hotspot. Have you had a similar situation? Is there any way to solve this problem?

**Comment by mrasong** [comment]
Try to use the latest  [AirportItlwm.kext](https://github.com/OpenIntelWireless/itlwm/releases), may helps you.
