### ISSUE TITLE
Thunderbolt Monitor After 12.3

### ISSUE THREAD

**Issue by SalvatoreAD** [hackintosh-efi/intel-nuc10#54]
hi, after the update to 12.3 monterey, the monitor connected with USB type c is no longer recognized. to solve I connected the monitor with HDMI.

**Comment by mrasong** [comment]
Dual monitor? 
Mine works well with a 1080P type-c to HDMI monitor and a 4k HDMI monitor.
Try to set the primary display to Thunder Bolt in BIOS, see whether it works.

**Comment by SalvatoreAD** [comment]
No. i only have a Monitor with type-c to type-c. I tried to set it from the bios but nothing. before the update everything was working fine.

**Comment by mrasong** [comment]
Update to 12.3.1 may fix this bug.
