### ISSUE TITLE
OC 0.7.9安装Monterey12.3，不接显示器，无法进入系统，死机状态

### ISSUE THREAD

**Issue by wellsng** [hackintosh-efi/intel-nuc10#58]

**Comment by mrasong** [comment]
未出现这种情况，建议清下nvram再试试

**Comment by wellsng** [comment]
确实有此情况，在monterey12.3下发生的在其他系统是没有问题的，就是不接任何显示器，是无法进入系统的，BIOS也是升级到最新版本，不清楚是什么原因导致的，不知道是不是系统的问题，我后续尝试重新安装系统试一下

**Comment by mrasong** [comment]
升级到12.3.1试试
