### ISSUE TITLE
applealc problem

### ISSUE THREAD

**Issue by xz021980** [hackintosh-efi/intel-nuc10#6]
Hi,
I test the EFI on my nuc10i5fnh.
The problem is applealc only working with display when display and hdmi plugin same time.
Only display or Only hdmi applealc not work!!

How to fix it? Thx.
BR

**Comment by mrasong** [comment]
you can use `/EFI/OC/config.VoodooHDA.plist` which enabled `VoodooHDA.kext` to fix HDMI audio issue. 
more info please go to README.

**Comment by enderaltin** [comment]
Why HDMI audio not working with AppleAlc?
Do you have a prediction?

**Comment by xz021980** [comment]
> Why HDMI audio not working with AppleAlc?
> Do you have a prediction?

I really use this EFI to Boot my MacOS...
But HDMI audio not working with AppleAlC on my machine.
You can see the HDMI audio issue on  README.
