### ISSUE TITLE
no drive detected after install

### ISSUE THREAD

**Issue by mghz** [hackintosh-efi/intel-nuc10#69]
I was able to create the usb and boot it, erased the ssd drive and started the install. It copies all the files but on reboot it seems the drive becomes undetectable and it detects the usb only. 

from the instructions when performing "Choose CFGLock Shell.efi unlock CFG." it prompts for too options for that setting but none are the one pointed out!

**Comment by mghz** [comment]
I tried it again and it worked this time, the setup completes and the OS loads. now when I take out the USB, the drive is not recognizable as bootable anymore. I'm assuming the EFI files are not copied over to the actual main SSD drive!

**Comment by essereio** [comment]
No they aren't. You're suppose to use EFI Agent right away after the first boot to mount the EFI partition on the main drive and copy the EFI folder to the EFI partition on the main drive. Re-install and try again.

Copy EFI Agent app to the USB drive.

https://github.com/headkaze/EFI-Agent

**Comment by mghz** [comment]
yes I realized that after running the installer a couple of times. it's working now. thanks.
