### ISSUE TITLE
Anyone tried this EFI with the Ventura Beta?

### ISSUE THREAD

**Issue by ejh4286** [hackintosh-efi/intel-nuc10#78]

**Comment by ejh4286** [comment]
Update: I've tried thus efi with ventura beta. It installs and works for a minute then crashes.  I'm unsure of the problem. I suspect something in Ventura is creating some conflict that is not present in Monterey. Works great in Monterey.

**Comment by HawkysCC** [comment]
Please update your lilu.kext to the latest version,and add -lilubetaall to your boot-args.It should work.

**Comment by jktan-arrivo** [comment]
Is this version supported for Ventura already ?

**Comment by mrasong** [comment]
> 

Replace the [`AirportItlwm`](https://github.com/OpenIntelWireless/itlwm/releases/download/v2.2.0-alpha/AirportItlwm-Ventura-v2.2.0-DEBUG-alpha-ee56708.zip) with ventura version, and then update it.

**Comment by jktan-arrivo** [comment]
@mrasong Thanks for your answer.
Could you explain the way to replace it ? 

Thank you so much.

**Comment by mrasong** [comment]
> 

Just replace `/EFI/OC/Kexts/AirportItlwm.kext` with which you download for Ventura.

**Comment by mrasong** [comment]
> @mrasong Thanks for your answer. Could you explain the way to replace it ?
> 
> Thank you so much.

new efi with OC 0.8.6 Ventura default released.

**Comment by jktan-arrivo** [comment]
@mrasong thanks !!
how to be smart like you ?

**Comment by jktan-arrivo** [comment]
sorry guys. anyone knows where to download the ventura installer ?
https://dortania.github.io/OpenCore-Install-Guide/installer-guide/winblows-install.html#downloading-macos

![Screen Shot 2022-11-10 at 8 29 44 AM](https://user-images.githubusercontent.com/109949861/200995094-c51da2a4-4e38-4221-b262-2dcc40ac7a6e.png)
