### ISSUE TITLE
Can't wake on USB

### ISSUE THREAD

**Issue by lampk9015** [hackintosh-efi/intel-nuc10#79]
Hi,

My NUC10i5FNH can sleep/wake normally but wake on the power button only, can not wake on the USB.
I want to ask that is it possible? If yes, how can I make it work?
I tried 3 methods in here https://dortania.github.io/OpenCore-Post-Install/usb/misc/keyboard.html but nothing worked.
I use Catalina 19H2026 with OC 0.8.4, if you need more info, please ask.
Thank you very much.

**Comment by mrasong** [comment]
For now we can only wake up from the power button.
