### ISSUE TITLE
Thunderbolt 3

### ISSUE THREAD

**Issue by basett1** [hackintosh-efi/intel-nuc10#8]
Hi, the Thunderbolt Port Is full working in your EFI?? Because in mine i see only in PCIe tab and not in the Thunderbolt tabs. And connected with a Windows PC with Thunderbolt the nuc is not recognized.

You think the flash Is needed?

**Comment by mrasong** [comment]
The thunderbolt has not yet fully support, only can run with type-c mode, such as Type-c to HDMI hub, type-c monitor , etc.

**Comment by hotsticker** [comment]
Does audio output to HDMI through type-c to HDMI port with AppleALC.kext?

**Comment by claud9999** [comment]
Given this was 2 years ago, I'm wondering if there's any progress on Thunderbolt 3 support? I loved using networking over it to talk from my iMac to my Linux-based RAID system. I can continue to do this over Ethernet but nothing like Thunderbolt networking!

**Comment by mrasong** [comment]
> 

The last few versions already support Thunderbolt.
You can check the release note.
Hot plug is not supported.

**Comment by claud9999** [comment]
Hmm, well I used the "HEAD" of the repo a few days ago and MacOS wouldn't establish a network connection over the Thunderbolt connection (which I had successfully used for years with my iMac.) Thoughts? I can try again today.

**Comment by claud9999** [comment]
> Hmm, well I used the "HEAD" of the repo a few days ago and MacOS wouldn't establish a network connection over the Thunderbolt connection (which I had successfully used for years with my iMac.) Thoughts? I can try again today.

Tried today (sorry for the delay), still no Thunderbolt network connection in Ventura.
