### ISSUE TITLE
typec显示器唤醒问题

### ISSUE THREAD

**Issue by raydoom** [hackintosh-efi/intel-nuc10#82]
opencore0.8.4，系统版本12.6
使用typec转dp线连接显示器，锁定屏幕后，过几秒钟，显示器显示无信号输入，按键盘唤醒，显示器表现为被唤醒（但是一直黑屏，此时系统正常，远程能连接，按大写锁定键也能确认系统正常）几秒钟后，显示器显示无信号输入，只有长按nuc电源键，几秒后显示器正常点亮，进入系统

**Comment by Pidbid** [comment]
目前只能电源键唤醒
