### ISSUE TITLE
Ventura full install stuck at gray screen after language selection

### ISSUE THREAD

**Issue by claud9999** [hackintosh-efi/intel-nuc10#94]
Ok I have installed bios 055 and did the CFG unlock; the Ventura installer (full installer) starts and asks for my language but then doesn't go any further. The mouse is responsive but the screen is a solid gray. Thoughts? I may try Monterey (with affiliated config.plist).

**Comment by mrasong** [comment]
What SSD are you using for?

**Comment by mrasong** [comment]
WD SN550 SN750 SN570 SN770 maybe a better choice, some samsung ssd CAN NOT hackintosh on NUC10

**Comment by claud9999** [comment]
Micron 1100 MT (2TB), if the model SSD is important, I can buy one and try again.

**Comment by claud9999** [comment]
Sure enough, removing the SSD entirely got me past the language selection screen. I'll try other SSD's I have on hand to see if I can get one that has joy. Thanks for the suggestion!
